services:  
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment: 
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: dbt_dev
    ports:
      - "5432:5432"