dbt_sample:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: test_user
      password: test_pass
      port: 5432
      dbname: dbt_dev
      schema: public
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
